### ISSUE TITLE
unable to pay 

### ISSUE THREAD

**Issue by temamawelu** [Chapa-Et/sdk-examples#2]
\chappa\
GuzzleHttp\Exception\RequestException
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.chapa.co/v1/transaction/initialize

**Comment by isrugeek** [comment]
I am assuming `chappa` is declared somewhere. It could be a firewall issue. 

P.S: I am closing this issue feel free to reopen it again.
